language: android
jdk:
  - oraclejdk8
android:
  components:
    # Installs the repos to be able to download additional components below
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_cache:
  # Remove the lock file as per https://docs.travis-ci.com/user/languages/android#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    # So we dont have to redownload gradle on each build
    - $HOME/.gradle

before_install:
  # Decrypt the release keystore
  - echo ${CI_RELEASE_KEYSTORE_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/release_key.keystore.gpg" > UoitDCLibraryBooking/release_key.keystore
  # Decrypt the google play api key
  - echo ${CI_GOOGLE_PLAY_API_KEY_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/google_play_android_developer_api_keys.json.gpg" > UoitDCLibraryBooking/google_play_android_developer_api_keys.json

script:
  - ./scripts/set_release_track_env_variable_based_on_ci_branch.sh
  - ./gradlew publishApkRelease -Dorg.gradle.project.track=${ANDROID_APK_RELEASE_TRACK}

# Must be present. DO NOT REMOVE
branches:
  only:
    - master
    - beta

notifications:
  slack:
    secure: mYIFi0udue0C8Oh0vZ54B89aNYyoD5Y5R92SrtNDYWeZMgjL2U3EEHpnyKZpJ5fjMFF9UIt2dKi2otr1xMc3UQmVfMWmv5ikVk/x1SuhkfJ85b3BId1TqbJGoRvpzRAE3E6HaZQAnWCM1HWziZs8ShhWuNo56FcbK8JWD7evcsdsgQnVLsdj9ktBX6NgYRCTjZX3UZ8bS864twAkm4SJwkxmmRvGt7nX5nU9MQ9Pj4N+w0lnzkdRc4kLiKhoMJOoyJRfSv3/w9APece1LhdBfPGsxbWOkdAq/ZjwGXvVN6DARMjVrZzEVfLxBHV+pqRcnK+eFolOr47M4L2APCB51b1fFn6gpMQzi2vJ8GAGCYCqLuxKu0LdWJjaT+1whrS4yWajFOBxEwBxUfb7Cs31bDWVrtwJ5c68YJTPKmkm8RAIjectlkM+QJcbKmvUBw5qhZzSndI/2nl7S57/SuDlHIXXjZNKGpRoV/WbvaAZuiYIxwrNL+l2fKGTAWXHY6Agsf8sUoofoqru1U58WpimJhftzqkXohIFXnBR412W8oBdY5xpf97WR83poKwsu0dlHmXpAZ3hfeR+oSL9QUamZ86mCzmstNwJqxi6bUut+6iBb/JnzEc+4o/9/pGXLEUA31KJFV363yGsT5Yx+oc8hyUB4qeFnwze6F4bdeXqlOs=
after_success:
  # Create Git Tag
  - git config --global user.email "uoitdclibrarybooking@objectivetruth.ca"
  - git config --global user.name "Travis CI"
  # Reset the ANDROID_APK_RELEASE_TRACK env variable since its wiped when after_success starts
  - export ANDROID_APK_RELEASE_TRACK=`cat .travis_branch_name`
  - echo -n $GIT_TAG > version.txt
  - git commit -m "Set build VERSION number" version.txt
  - export GIT_TAG=v1.$(expr 20020 + ${TRAVIS_BUILD_NUMBER})-${ANDROID_APK_RELEASE_TRACK}
  - echo ${GIT_TAG}
  - git tag -a --file="UoitDCLibraryBooking/src/main/assets/whatsnew_thisversion.txt" $GIT_TAG
  - git push --quiet https://$GH_TOKEN@github.com/ObjectiveTruth/UoitDCLibraryBooking.git $GIT_TAG > /dev/null 2>&1
  # Rename release apk file
  - mv UoitDCLibraryBooking/build/outputs/apk/UoitDCLibraryBooking-release.apk
    UoitDCLibraryBooking/build/outputs/apk/UoitDCLibraryBooking_${GIT_TAG}.apk

deploy:
  provider: releases
  api_key:
    secure: goZT2pPYFPu2+vYafTqPwXeTd6TDOd2TzRv4c5zdh8Z6hS2G45Fr0ACAOApLNeB0eCur9qthbWQPNF1rQRGg0ghlRHJCkruFi0wg0CwzSFBkdXAEYjptbcpP7hYcVWq4bRb9v53ISA0+cbhOIAWvexhHuJq/d1s68aA1llLLWWJhdVXo8i1VWMBSbAHMBmzyIKmoiX1QYKBgMNP8tpG1cxpG6MdEwHKVd+KFsSYYECv25Ak5pJCe2zcORej+PeuXs3FT6+jp/zc86qrx/LiiAdKJS7o7ZBoFYKtP6w2qq56CUDW3EdzdwBMwTFZalP3zQHR04cwatBgDscAzsEqapRiOXv6KL9yh6vB65T7uwyVMrX7BvXdG1vcCDzSAaFjBkSGcXcTOoDscvSuz7+q68XgFU9m2zZQZMjydArY6mxXV5rgdgDtyOvvBwu1kqswH4qJgiOyUbIpt9Tuvki2LcZYaEN67LriYx7QYf1Bqt6bg9ACuuzY5MRxX772abBMlrdJZwmg8aGMrb/Rr19VSsymxwX08fe5YvMCjSoDmZ//kFdPkEmw7milFlO0WkCLHW34z3W5XgcpkIlSK1oFBmtO0sHxeys8cXpUKtR8Nnf70Vgh4Qr5EUd6bAnq/zdDwtLkf5R6KjZN0VZjRgWKbwv3KE1sFT40YRQkYvlGctR8=
  file: "UoitDCLibraryBooking/build/outputs/apk/UoitDCLibraryBooking_v*.apk"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    repo: ObjectiveTruth/UoitDCLibraryBooking
env:
  global:
    secure: YtrKwhb5BnhRujck9BVjUQwd8Y/++BIKDITCOPdnzrvK18Luw/S9BOKSlI2pqVpepN6prkpPLKKkuSsyi+p5lA05fvQwCE9StuwXK2sKX9RjV9q2foK6eYddU2/OWbg8AUwKOzl+uRC7W3y/ncSmofouonkK+EopC7u0HRfPSpoAkKW6c0bW2kdp1epsvSCqnQ4ZTmTFYw850tEM51CuPfnc0VIr1pmFq9x9jJhNj5HB7b3QdkLatcwJcacEwFlkOdElPBgiBuK/CfC+/hy2gtdXgiOXIQ/3U4047UC2gfNtV28luFANocgdjp9idpUU6gT+DfQ59KqgPLjSxmMd6VgUMKmvRcRujv8Jd9Y4yBF3dkpdCISCAdSbPEk3CyV65BBKU6dQa5jh07tEyr0ucHwuxKz699atAj9b9KVE4DXpQjwMCJDW+xapz99D7ZpjwkzlGoTuns7+6Qvd1IQAsMmY+EipIT1TUMvoDOHinBilJZ4lsDSK2GiYls/JgHyfMXL00YSjVIHRdU6d/dYfJK+tCPoQBhj46ezeZ7awBcQG1AAoLMBWKKLobrk5ez510Chp0KCuZ+rzKeroPbzbJDclSrrd/09zakFPLpP9SS0Pm4M8oMT18pvl4y2pWnlHhx/LfG9akQ/3wTbvJjrZdSqekJZS4ETDrQWnNWB5lc0=

