language: android
android:
  components:
    # Installs the repos to be able to download additional components below
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
before_cache:
  # Remove the lock file as per https://docs.travis-ci.com/user/languages/android#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    # So we dont have to redownload gradle on each build
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # Decrypt the release keystore
  - echo ${CI_RELEASE_KEYSTORE_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/release_key.keystore.gpg" > UoitDCLibraryBooking/release_key.keystore
  # Decrypt the google play api key
  - echo ${CI_GOOGLE_PLAY_API_KEY_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/google_play_android_developer_api_keys.json.gpg" > UoitDCLibraryBooking/google_play_android_developer_api_keys.json

script:
  - ./scripts/set_release_track_env_variable_based_on_ci_branch.sh
  - ./gradlew publishApkRelease -Dorg.gradle.project.track=${ANDROID_APK_RELEASE_TRACK}

# Must be present. DO NOT REMOVE
branches:
  only:
    - master
    - beta

notifications:
  slack: ${SLACK_CHANNEL_AND_API_TOKEN}
after_success:
  # Create Git Tag
  - git config --global user.email "uoitdclibrarybooking@objectivetruth.ca"
  - git config --global user.name "Travis CI"
  - echo -n $GIT_TAG > version.txt
  - git commit -m "Set build VERSION number" version.txt
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet https://$GH_TOKEN@github.com/ObjectiveTruth/UoitDCLibraryBooking.git $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  api_key:
    secure: goZT2pPYFPu2+vYafTqPwXeTd6TDOd2TzRv4c5zdh8Z6hS2G45Fr0ACAOApLNeB0eCur9qthbWQPNF1rQRGg0ghlRHJCkruFi0wg0CwzSFBkdXAEYjptbcpP7hYcVWq4bRb9v53ISA0+cbhOIAWvexhHuJq/d1s68aA1llLLWWJhdVXo8i1VWMBSbAHMBmzyIKmoiX1QYKBgMNP8tpG1cxpG6MdEwHKVd+KFsSYYECv25Ak5pJCe2zcORej+PeuXs3FT6+jp/zc86qrx/LiiAdKJS7o7ZBoFYKtP6w2qq56CUDW3EdzdwBMwTFZalP3zQHR04cwatBgDscAzsEqapRiOXv6KL9yh6vB65T7uwyVMrX7BvXdG1vcCDzSAaFjBkSGcXcTOoDscvSuz7+q68XgFU9m2zZQZMjydArY6mxXV5rgdgDtyOvvBwu1kqswH4qJgiOyUbIpt9Tuvki2LcZYaEN67LriYx7QYf1Bqt6bg9ACuuzY5MRxX772abBMlrdJZwmg8aGMrb/Rr19VSsymxwX08fe5YvMCjSoDmZ//kFdPkEmw7milFlO0WkCLHW34z3W5XgcpkIlSK1oFBmtO0sHxeys8cXpUKtR8Nnf70Vgh4Qr5EUd6bAnq/zdDwtLkf5R6KjZN0VZjRgWKbwv3KE1sFT40YRQkYvlGctR8=
  file: "UoitDCLibraryBooking/build/outputs/apk/*.apk"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    repo: ObjectiveTruth/UoitDCLibraryBooking
env:
  global:
    secure: YtrKwhb5BnhRujck9BVjUQwd8Y/++BIKDITCOPdnzrvK18Luw/S9BOKSlI2pqVpepN6prkpPLKKkuSsyi+p5lA05fvQwCE9StuwXK2sKX9RjV9q2foK6eYddU2/OWbg8AUwKOzl+uRC7W3y/ncSmofouonkK+EopC7u0HRfPSpoAkKW6c0bW2kdp1epsvSCqnQ4ZTmTFYw850tEM51CuPfnc0VIr1pmFq9x9jJhNj5HB7b3QdkLatcwJcacEwFlkOdElPBgiBuK/CfC+/hy2gtdXgiOXIQ/3U4047UC2gfNtV28luFANocgdjp9idpUU6gT+DfQ59KqgPLjSxmMd6VgUMKmvRcRujv8Jd9Y4yBF3dkpdCISCAdSbPEk3CyV65BBKU6dQa5jh07tEyr0ucHwuxKz699atAj9b9KVE4DXpQjwMCJDW+xapz99D7ZpjwkzlGoTuns7+6Qvd1IQAsMmY+EipIT1TUMvoDOHinBilJZ4lsDSK2GiYls/JgHyfMXL00YSjVIHRdU6d/dYfJK+tCPoQBhj46ezeZ7awBcQG1AAoLMBWKKLobrk5ez510Chp0KCuZ+rzKeroPbzbJDclSrrd/09zakFPLpP9SS0Pm4M8oMT18pvl4y2pWnlHhx/LfG9akQ/3wTbvJjrZdSqekJZS4ETDrQWnNWB5lc0=

