language: android
android:
  components:
    # Installs the repos to be able to download additional components below
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
before_cache:
  # Remove the lock file as per https://docs.travis-ci.com/user/languages/android#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    # So we dont have to redownload gradle on each build
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  # Decrypt the release keystore
  - echo ${CI_RELEASE_KEYSTORE_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/release_key.keystore.gpg" > UoitDCLibraryBooking/release_key.keystore
  # Decrypt the google play api key
  - echo ${CI_GOOGLE_PLAY_API_KEY_GPG_PASSPHRASE} | gpg --batch --passphrase-fd 0 --decrypt "UoitDCLibraryBooking/google_play_android_developer_api_keys.json.gpg" > UoitDCLibraryBooking/google_play_android_developer_api_keys.json

script:
  - ./scripts/set_release_track_env_variable_based_on_ci_branch.sh
  - ./gradlew publishApkRelease -Dorg.gradle.project.track=${ANDROID_APK_RELEASE_TRACK}

# Must be present. DO NOT REMOVE
branches:
  only:
    - some_branch_that_should_never_exist
